name: qbittorent
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    ports:
      - "${IFACE}:${WEBUI_PORT}:${WEBUI_PORT}"
      - "${IFACE}:${TORRENT_PORT}:54356"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - config:/config
      - data:/data
      - ${DATA_FOLDER}:/downloads
    restart: unless-stopped
volumes:
  config:
  data:
