services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${IFACE}:${DNS_PORT}:53/tcp"
      - "${IFACE}:${DNS_PORT}:53/udp"
      - "${IFACE}:${WEB_PORT}:80/tcp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=unbound;unbound
    volumes:
      - pihole_conf:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
  
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    restart: unless-stopped

volumes:
  pihole_conf:
  pihole_dnsmasq:
